In [1]:
from scipy import stats
from sklearn import datasets,linear_model,discriminant_analysis,cross_validation
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import time
import gc
import json
import scipy.stats as ss
from scipy.stats import chi2_contingency
from scipy.stats import mode
from Library import get_sample
from Library import optimal_binning
from sklearn import cross_validation,metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn import linear_model
from sklearn import ensemble
from sklearn.ensemble import GradientBoostingClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.grid_search import GridSearchCV
import xgboost as xgb
from sqlalchemy.engine import create_engine
engine_1 = create_engine(
        'mysql+pymysql://ro:cKqj4E3$K7GGeqs@nshd-slave-bi.mysql.rds.aliyuncs.com/paydayloan?charset=utf8',
        echo=False,pool_size=20, max_overflow=0)
engine_2 = create_engine(
    'mysql+pymysql://riskcontrol:tuLwJ3G6FLwR6t4A@nshd-risk.mysql.rds.aliyuncs.com/riskcontrol?charset=utf8',
    echo=False)

/usr/local/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py:1078: UserWarning: Illegal line #210
	"			 Verdana, Geneva, Lucid, Arial, Helvetica, Avant Garde, 
"
	in file "/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc"
  warnings.warn('Illegal %s' % error_details)
/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py:1078: UserWarning: Illegal line #211
	"			sans-serif
"
	in file "/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc"
  warnings.warn('Illegal %s' % error_details)


In [2]:
sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata \
            where startDate >= '2017-10-15' and endDate < '2017-12-5')a \
        where overduedays is not null and uid >= 100;"
users = pd.read_sql(sql,engine_2)

sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata \
            where startDate >= '2017-10-15' and endDate < '2017-12-5')a \
        where overduedays is not null and overduedays > 0 and uid >= 100;"
users1 = pd.read_sql(sql,engine_2)

sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata)a \
        where overduedays is not null and uid >= 100;"
Users = pd.read_sql(sql,engine_2)

sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata)a \
        where overduedays is not null and overduedays > 0 and loan_time = 1 and uid >= 100;"
Users1 = pd.read_sql(sql,engine_2)

In [14]:
# #label1
# sql = "select distinct uid from ydata where startDate >= '2017-10-15' and overduedays is not null;"


# sql = "select distinct uid from ydata \
#         where startDate >= '2017-10-15' and overduedays is not null and overduedays > 0;"
# users1 = pd.read_sql(sql,engine_2)

# #label
# sql = "select distinct uid from ydata where overduedays is not null;"
# Users = pd.read_sql(sql,engine_2)

# sql = "select distinct uid from ydata where overduedays is not null and overduedays > 0;"
# Users1 = pd.read_sql(sql,engine_2)

In [5]:
#总的数据
#user对应的label
start = time.clock()
Users = list(Users.uid)
Users1 = list(Users1.uid)
Label = [1 if Users[i] in Users1 else 0 for i in range(len(Users))]
userTarget = pd.DataFrame([Users,Label]).T
userTarget.columns = ['uid','target']
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 47.90 s


In [6]:
def DividConCat(features_df):
    start = time.clock()
    #将变量分为离散变量和连续变量
    var_name = list(features_df.columns)
    try:
        var_name.remove('uid')
        var_name.remove('target')
    except:
        0
    data = features_df.fillna(-1)
    target = list(features_df['target'])
    ConVar = []
    CatVar = []
    for var in var_name:
        values = list(data[var])
    #     values_1 = [values[i] for i in range(len(values)) if target[i] == 1]
        if len(list(set(values))) < 6:
            CatVar.append(var)
    #         thread = 0
    #         for val in values:
    #             if values.count(val)/len(values) > 0.9 and values_1.count(val)/len(values_1) > 0.9:
    #                 thread = 1
    #                 break
    #         if thread == 0:
    #             CatVar.append(var)
    #     else:
        else:
            ConVar.append(var)
    features_df_con = features_df[['uid','target']+ConVar]
    features_df_cat = features_df[['uid','target']+CatVar]
    end = time.clock()
    print("run time: %.2f min %.2f s" % divmod((end - start), 60))
    return(ConVar,CatVar,features_df_con,features_df_cat)

In [7]:
# 两个分类变量的相关性检验(转化为独立性检验)
# 以及关联系数(Phi coefficient,又称作 Cramer's statistic)
def CatVarCorrP(features_df,CatVar):
    """ calculate Cramers V statistic for categorial-categorial association.
        uses correction from Bergsma and Wicher, 
        Journal of the Korean Statistical Society 42 (2013): 323-328
    """
    #离散变量的筛选
    start = time.clock()
    target = features_df.target
    dic_var_corrp = {}
    for var in CatVar:
        values = features_df[var]
        confusion_matrix = pd.crosstab(target,values)
        chi2,p,dof,expected = ss.chi2_contingency(confusion_matrix)
        n = confusion_matrix.sum().sum()
        phi2 = chi2/n
        r,k = confusion_matrix.shape
        phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))    
        rcorr = r - ((r-1)**2)/(n-1)
        kcorr = k - ((k-1)**2)/(n-1)
        corr = np.sqrt(phi2corr / min((kcorr-1), (rcorr-1)))
        dic_var_corrp[var] = [corr,p]
    end = time.clock()
    print("run time: %.2f min %.2f s" % divmod((end - start), 60))
    return(dic_var_corrp)

In [8]:
#卡方检验
def CatVarChi(features_df,CatVar):
    start = time.clock()
    dic_var_pval = {}
    data = features_df.fillna(-1)
    target = list(features_df['target'])
    for var in CatVar:
        values = list(data[var])
        values_0 = [values[i] for i in range(len(values)) if target[i]==0]
        values_1 = [values[i] for i in range(len(values)) if target[i]==1]
        stand = list(set(values))
        chi_0 = []
        chi_1 = []
        for val in stand:
            if val != -1:
                chi_0.append(values_0.count(val))
                chi_1.append(values_1.count(val))
        chi = np.array([chi_0,chi_1])
        chi_result = chi2_contingency(chi)
        dic_var_pval[var] = chi_result[1]
    end = time.clock()
    print("run time: %.2f min %.2f s" % divmod((end - start), 60))
    return(dic_var_pval)

In [157]:
start = time.clock()
sql = 'select * from lr_91;'
features_91 = pd.read_sql(sql,engine_2)
features_91 = pd.merge(userTarget,features_91,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 14.58 s


In [158]:
ConVar,CatVar,features_91_con,features_91_cat = DividConCat(features_91)
features_91_con.to_csv(r'/home/heyang/data/features_lr/features_91.csv',index=False)
dic_91var_corrp = CatVarCorrP(features_91,CatVar)
dic_91var_chipval = CatVarChi(features_91,CatVar)

run time: 0.00 min 0.80 s
run time: 0.00 min 0.69 s
run time: 0.00 min 2.23 s


In [159]:
start = time.clock()
sql = 'select * from lr_basic;'
features_basic = pd.read_sql(sql,engine_2)
features_basic = pd.merge(userTarget,features_basic,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 25.91 s


In [160]:
ConVar,CatVar,features_basic_con,features_basic_cat = DividConCat(features_basic)
features_basic_con.to_csv(r'/home/heyang/data/features_lr/features_basic.csv',index=False)
dic_basicvar_corrp = CatVarCorrP(features_basic,CatVar)
dic_basicvar_chipval = CatVarChi(features_basic,CatVar)

run time: 0.00 min 1.22 s
run time: 0.00 min 2.28 s
run time: 0.00 min 7.37 s


In [161]:
start = time.clock()
sql = 'select * from lr_call_record;'
features_call = pd.read_sql(sql,engine_2)
features_call = pd.merge(userTarget,features_call,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 55.33 s


In [162]:
ConVar,CatVar,features_call_con,features_call_cat = DividConCat(features_call)
features_call_con.to_csv(r'/home/heyang/data/features_lr/features_call.csv',index=False)
dic_callvar_corrp = CatVarCorrP(features_call,CatVar)
dic_callvar_chipval = CatVarChi(features_call,CatVar)

run time: 0.00 min 3.05 s
run time: 0.00 min 3.92 s
run time: 0.00 min 12.73 s


In [163]:
start = time.clock()
sql = 'select * from lr_hd;'
features_hd = pd.read_sql(sql,engine_2)
features_hd = pd.merge(userTarget,features_hd,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 8.64 s


In [164]:
ConVar,CatVar,features_hd_con,features_hd_cat = DividConCat(features_hd)
features_hd_con.to_csv(r'/home/heyang/data/features_lr/features_hd.csv',index=False)
dic_hdvar_corrp = CatVarCorrP(features_hd,CatVar)
dic_hdvar_chipval = CatVarChi(features_hd,CatVar)

run time: 0.00 min 0.61 s
run time: 0.00 min 0.28 s
run time: 0.00 min 0.81 s


In [341]:
start = time.clock()
sql = 'select * from lr_sms;'
features_sms = pd.read_sql(sql,engine_2)
features_sms = pd.merge(userTarget,features_sms,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 9.08 s


In [342]:
ConVar,CatVar,features_sms_con,features_sms_cat = DividConCat(features_sms)
features_sms_con.to_csv(r'/home/heyang/data/features_lr/features_sms.csv',index=False)
dic_smsvar_corrp = CatVarCorrP(features_sms,CatVar)
dic_smsvar_chipval = CatVarChi(features_sms,CatVar)

run time: 0.00 min 0.70 s
run time: 0.00 min 0.02 s
run time: 0.00 min 0.13 s


In [9]:
start = time.clock()
sql = 'select * from lr_td;'
features_td = pd.read_sql(sql,engine_2)
features_td = pd.merge(userTarget,features_td,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 5.64 s


In [168]:
ConVar,CatVar,features_td_con,features_td_cat = DividConCat(features_td)
features_td_con.to_csv(r'/home/heyang/data/features_lr/features_td.csv',index=False)
dic_tdvar_corrp = CatVarCorrP(features_td,CatVar)
dic_tdvar_chipval = CatVarChi(features_td,CatVar)

run time: 0.00 min 0.24 s
run time: 0.00 min 0.26 s
run time: 0.00 min 0.80 s


In [12]:
start = time.clock()
sql = 'select * from lr_zmxy;'
features_zmxy = pd.read_sql(sql,engine_2)
features_zmxy = pd.merge(userTarget,features_zmxy,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 5.30 s


In [170]:
ConVar,CatVar,features_zmxy_con,features_zmxy_cat = DividConCat(features_zmxy)
features_zmxy_con.to_csv(r'/home/heyang/data/features_lr/features_zmxy.csv',index=False)
dic_zmxyvar_corrp = CatVarCorrP(features_zmxy,CatVar)
dic_zmxyvar_chipval = CatVarChi(features_zmxy,CatVar)

run time: 0.00 min 0.33 s
run time: 0.00 min 0.45 s
run time: 0.00 min 1.39 s


In [171]:
#整合离散变量的指标
dic_var_corrp = {}
dic_var_corrp = dict(dic_var_corrp,**dic_91var_corrp)
dic_var_corrp = dict(dic_var_corrp,**dic_basicvar_corrp)
dic_var_corrp = dict(dic_var_corrp,**dic_callvar_corrp)
dic_var_corrp = dict(dic_var_corrp,**dic_hdvar_corrp)
dic_var_corrp = dict(dic_var_corrp,**dic_smsvar_corrp)
dic_var_corrp = dict(dic_var_corrp,**dic_tdvar_corrp)
dic_var_corrp = dict(dic_var_corrp,**dic_zmxyvar_corrp)

In [173]:
for var in dic_91var_corrp.keys():
    dic_var_corrp[var].append(dic_91var_chipval[var])
for var in dic_basicvar_corrp.keys():
    dic_var_corrp[var].append(dic_basicvar_chipval[var])
for var in dic_callvar_corrp.keys():
    dic_var_corrp[var].append(dic_callvar_chipval[var])
for var in dic_hdvar_corrp.keys():
    dic_var_corrp[var].append(dic_hdvar_chipval[var])
for var in dic_smsvar_corrp.keys():
    dic_var_corrp[var].append(dic_smsvar_chipval[var])
for var in dic_tdvar_corrp.keys():
    dic_var_corrp[var].append(dic_tdvar_chipval[var])
for var in dic_zmxyvar_corrp.keys():
    dic_var_corrp[var].append(dic_zmxyvar_chipval[var])

In [176]:
varvalues = []
for var in dic_var_corrp.keys():
    varval = []
    varval.append(var)
    varval = varval + dic_var_corrp[var]
    varvalues.append(varval)
varvalues = pd.DataFrame(varvalues,columns=['varname','corr','p','chip'])

In [351]:
dic_var_corrp['one_hot_relatStatus_married'],dic_var_corrp['one_hot_DEFAULT'],dic_var_corrp['one_hot_ANDROID_APP']

([0.061527665261344434, 1.1256354798453339e-65, 1.1256354798453339e-65],
 [0.052633864830512266, 1.3248841519939268e-48, 1.3248841519939268e-48],
 [0.065066798904108158, 3.3425866428825285e-73, 3.3425866428825285e-73])

In [178]:
varvalues.to_csv(r'/home/heyang/data/features_lr/catvarindex.csv',index=False)

In [192]:
CatVarSave = []
varvalues_fill = varvalues.fillna(0)
for i in range(len(varvalues_fill)):
    if varvalues_fill.ix[i,1] > 0.05 and varvalues_fill.ix[i,2] < 0.01 and varvalues_fill.ix[i,3] < 0.01:
        CatVarSave.append(varvalues_fill.ix[i,0])

In [194]:
CatVarSave

['有过欠款',
 '还款状态次数_3',
 '还款状态次数_4',
 '借款状态_众数_1.0',
 '借款状态_众数_2.0',
 '批贷期数_众数_0.0',
 '批贷期数_众数_1.0',
 'one_hot_female',
 'one_hot_male',
 'one_hot_ANDROID_APP',
 'one_hot_DEFAULT',
 'one_hot_rOs_Android',
 'one_hot_rOs_iOS',
 'one_hot_relatStatus_married',
 'one_hot_relatStatus_single',
 '逾期特征_一天最大逾期数',
 'one_hot_V3_V_BC_CN_MA_UL180D',
 'one_hot_V3_V_BC_CN_MA_UM360D',
 'one_hot_F1_fail',
 'one_hot_F1_have_F1',
 'one_hot_F1_not_match']

In [207]:
#连续变量
features_con = features_91_con
features_con = pd.merge(features_con,features_basic_con.drop('target',1),how='left',on='uid')
features_con = pd.merge(features_con,features_call_con.drop('target',1),how='left',on='uid')
features_con = pd.merge(features_con,features_hd_con.drop('target',1),how='left',on='uid')
features_con = pd.merge(features_con,features_sms_con.drop('target',1),how='left',on='uid')
features_con = pd.merge(features_con,features_td_con.drop('target',1),how='left',on='uid')
features_con = pd.merge(features_con,features_zmxy_con.drop('target',1),how='left',on='uid')

In [211]:
features_con.to_csv(r'/home/heyang/data/features_lr/feautrescon.csv')

In [219]:
#总的数据
features = features_91
features = pd.merge(features,features_basic.drop('target',1),how='left',on='uid')
features = pd.merge(features,features_call.drop('target',1),how='left',on='uid')
features = pd.merge(features,features_hd.drop('target',1),how='left',on='uid')
features = pd.merge(features,features_sms.drop('target',1),how='left',on='uid')
features = pd.merge(features,features_td.drop('target',1),how='left',on='uid')
features = pd.merge(features,features_zmxy.drop('target',1),how='left',on='uid')

In [220]:
len(features),len(features.ix[0,:])

(79989, 805)

In [6]:
#2017-10-15号之后的数据
#user对应的label
start = time.clock()
users = list(users.uid)
users1 = list(users1.uid)
label = [1 if users[i] in users1 else 0 for i in range(len(users))]
usertarget = pd.DataFrame([users,label]).T
usertarget.columns = ['uid','target']
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 17.84 s


In [46]:
len(usertarget)

43945

In [8]:
start = time.clock()
sql = 'select * from lr_91;'
features1_91 = pd.read_sql(sql,engine_2)
features1_91 = pd.merge(usertarget,features1_91,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))
ConVar,CatVar,features1_91_con,features1_91_cat = DividConCat(features1_91)
features1_91_con.to_csv(r'/home/heyang/data/features_lr/features1/features1_91.csv',index=False)
dic_91var_corrp1 = CatVarCorrP(features1_91,CatVar)
dic_91var_chipval1 = CatVarChi(features1_91,CatVar)

run time: 0.00 min 15.79 s
run time: 0.00 min 0.43 s
run time: 0.00 min 0.63 s
run time: 0.00 min 1.34 s


In [9]:
start = time.clock()
sql = 'select * from lr_basic;'
features1_basic = pd.read_sql(sql,engine_2)
features1_basic = pd.merge(usertarget,features1_basic,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))
ConVar,CatVar,features1_basic_con,features1_basic_cat = DividConCat(features1_basic)
features1_basic_con.to_csv(r'/home/heyang/data/features_lr/features1/features1_basic.csv',index=False)
dic_basicvar_corrp1 = CatVarCorrP(features1_basic,CatVar)
dic_basicvar_chipval1 = CatVarChi(features1_basic,CatVar)

run time: 0.00 min 27.22 s
run time: 0.00 min 0.67 s
run time: 0.00 min 2.05 s
run time: 0.00 min 4.24 s


In [10]:
start = time.clock()
sql = 'select * from lr_call_record;'
features1_call = pd.read_sql(sql,engine_2)
features1_call = pd.merge(usertarget,features1_call,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))
ConVar,CatVar,features1_call_con,features1_call_cat = DividConCat(features1_call)
features1_call_con.to_csv(r'/home/heyang/data/features_lr/features1/features1_call.csv',index=False)
dic_callvar_corrp1 = CatVarCorrP(features1_call,CatVar)
dic_callvar_chipval1 = CatVarChi(features1_call,CatVar)

run time: 0.00 min 51.89 s
run time: 0.00 min 1.52 s
run time: 0.00 min 3.09 s
run time: 0.00 min 6.70 s


In [11]:
start = time.clock()
sql = 'select * from lr_hd;'
features1_hd = pd.read_sql(sql,engine_2)
features1_hd = pd.merge(usertarget,features1_hd,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))
ConVar,CatVar,features1_hd_con,features1_hd_cat = DividConCat(features1_hd)
features1_hd_con.to_csv(r'/home/heyang/data/features_lr/features1/features1_hd.csv',index=False)
dic_hdvar_corrp1 = CatVarCorrP(features1_hd,CatVar)
dic_hdvar_chipval1 = CatVarChi(features1_hd,CatVar)

run time: 0.00 min 8.66 s
run time: 0.00 min 0.33 s
run time: 0.00 min 0.20 s
run time: 0.00 min 0.40 s


In [12]:
start = time.clock()
sql = 'select * from lr_sms;'
features1_sms = pd.read_sql(sql,engine_2)
features1_sms = pd.merge(usertarget,features1_sms,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))
ConVar,CatVar,features1_sms_con,features1_sms_cat = DividConCat(features1_sms)
features1_sms_con.to_csv(r'/home/heyang/data/features_lr/features1/features1_sms.csv',index=False)
dic_smsvar_corrp1 = CatVarCorrP(features1_sms,CatVar)
dic_smsvar_chipval1 = CatVarChi(features1_sms,CatVar)

run time: 0.00 min 8.61 s
run time: 0.00 min 0.44 s
run time: 0.00 min 0.02 s
run time: 0.00 min 0.08 s


In [13]:
start = time.clock()
sql = 'select * from lr_td;'
features1_td = pd.read_sql(sql,engine_2)
features1_td = pd.merge(usertarget,features1_td,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))
ConVar,CatVar,features1_td_con,features1_td_cat = DividConCat(features1_td)
features1_td_con.to_csv(r'/home/heyang/data/features_lr/features1/features1_td.csv',index=False)
dic_tdvar_corrp1 = CatVarCorrP(features1_td,CatVar)
dic_tdvar_chipval1 = CatVarChi(features1_td,CatVar)

run time: 0.00 min 5.67 s
run time: 0.00 min 0.13 s
run time: 0.00 min 0.20 s
run time: 0.00 min 0.41 s


In [64]:
list(features1_td.columns)

['uid',
 'target',
 'bank_id',
 'bank_mobile',
 'mobile_id',
 'bank_mobile_id',
 'basescore',
 'bmTdrealScore',
 'emailScore',
 'final_score',
 'getpaidScore',
 'high_risk_num',
 'hit_num',
 'ID_overdue',
 'ID_overdueScore',
 'IDtooconnetScore',
 'infotooconnetScore',
 'item_ids_len',
 'landlineScore',
 'loadscore',
 'loan_7d',
 'locateExceptionScore',
 'low_risk_num',
 'medium_risk_num',
 'mobile_overdue',
 'mobile_overdueScore',
 'platformNUm1M',
 'platformNUm3M',
 'platformNUm7D',
 'QQ_overdueScore',
 'qz_score',
 'risk_items_num',
 'tdLoanScore',
 'one_hot_final_decision_Accept',
 'one_hot_final_decision_Reject',
 'one_hot_final_decision_Review']

In [14]:
start = time.clock()
sql = 'select * from lr_zmxy;'
features1_zmxy = pd.read_sql(sql,engine_2)
features1_zmxy = pd.merge(usertarget,features1_zmxy,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))
ConVar,CatVar,features1_zmxy_con,features1_zmxy_cat = DividConCat(features1_zmxy)
features1_zmxy_con.to_csv(r'/home/heyang/data/features_lr/features1/features1_zmxy.csv',index=False)
dic_zmxyvar_corrp1 = CatVarCorrP(features1_zmxy,CatVar)
dic_zmxyvar_chipval1 = CatVarChi(features1_zmxy,CatVar)

run time: 0.00 min 5.35 s
run time: 0.00 min 0.13 s
run time: 0.00 min 0.29 s
run time: 0.00 min 0.62 s


In [15]:
#整合离散变量的指标
dic_var_corrp1 = {}
dic_var_corrp1 = dict(dic_var_corrp1,**dic_91var_corrp1)
dic_var_corrp1 = dict(dic_var_corrp1,**dic_basicvar_corrp1)
dic_var_corrp1 = dict(dic_var_corrp1,**dic_callvar_corrp1)
dic_var_corrp1 = dict(dic_var_corrp1,**dic_hdvar_corrp1)
dic_var_corrp1 = dict(dic_var_corrp1,**dic_smsvar_corrp1)
dic_var_corrp1 = dict(dic_var_corrp1,**dic_tdvar_corrp1)
dic_var_corrp1 = dict(dic_var_corrp1,**dic_zmxyvar_corrp1)

In [16]:
for var in dic_91var_corrp1.keys():
    dic_var_corrp1[var].append(dic_91var_chipval1[var])
for var in dic_basicvar_corrp1.keys():
    dic_var_corrp1[var].append(dic_basicvar_chipval1[var])
for var in dic_callvar_corrp1.keys():
    dic_var_corrp1[var].append(dic_callvar_chipval1[var])
for var in dic_hdvar_corrp1.keys():
    dic_var_corrp1[var].append(dic_hdvar_chipval1[var])
for var in dic_smsvar_corrp1.keys():
    dic_var_corrp1[var].append(dic_smsvar_chipval1[var])
for var in dic_tdvar_corrp1.keys():
    dic_var_corrp1[var].append(dic_tdvar_chipval1[var])
for var in dic_zmxyvar_corrp1.keys():
    dic_var_corrp1[var].append(dic_zmxyvar_chipval1[var])

In [17]:
varvalues1 = []
for var in dic_var_corrp1.keys():
    varval = []
    varval.append(var)
    varval = varval + dic_var_corrp1[var]
    varvalues1.append(varval)
varvalues1 = pd.DataFrame(varvalues1,columns=['varname','corr','p','chip'])

In [198]:
varvalues1.to_csv(r'/home/heyang/data/features_lr/catvarindex1.csv',index=False)

In [ ]:
varvalues1

In [18]:
CatVarSave1 = []
varvalues1_fill = varvalues1.fillna(0)
for i in range(len(varvalues1_fill)):
    if varvalues1_fill.ix[i,1] > 0.05 and varvalues1_fill.ix[i,2] < 0.01 and varvalues1_fill.ix[i,3] < 0.01:
        CatVarSave1.append(varvalues1_fill.ix[i,0])

In [19]:
CatVarSave1

['逾期特征_一天最大逾期数',
 'one_hot_final_decision_Reject',
 'one_hot_final_decision_Review']

In [216]:
#连续变量
features1_con = features1_91_con
features1_con = pd.merge(features1_con,features1_basic_con.drop('target',1),how='left',on='uid')
features1_con = pd.merge(features1_con,features1_call_con.drop('target',1),how='left',on='uid')
features1_con = pd.merge(features1_con,features1_hd_con.drop('target',1),how='left',on='uid')
features1_con = pd.merge(features1_con,features1_sms_con.drop('target',1),how='left',on='uid')
features1_con = pd.merge(features1_con,features1_td_con.drop('target',1),how='left',on='uid')
features1_con = pd.merge(features1_con,features1_zmxy_con.drop('target',1),how='left',on='uid')

In [217]:
features1_con.to_csv(r'/home/heyang/data/features_lr/features1/feautrescon1.csv')

In [20]:
#所有的特征
features1 = features1_91
features1 = pd.merge(features1,features1_basic.drop('target',1),how='left',on='uid')
features1 = pd.merge(features1,features1_call.drop('target',1),how='left',on='uid')
features1 = pd.merge(features1,features1_hd.drop('target',1),how='left',on='uid')
features1 = pd.merge(features1,features1_sms.drop('target',1),how='left',on='uid')
features1 = pd.merge(features1,features1_td.drop('target',1),how='left',on='uid')
features1 = pd.merge(features1,features1_zmxy.drop('target',1),how='left',on='uid')

In [256]:
ConVarSave1 = ['SMS_已逾期']

In [310]:
VarSave1 = ConVarSave1 + CatVarSave1 + VarSave
VarSave1 = list(set(VarSave1))

In [29]:
VarSave1 = pd.read_csv(r'/home/heyang/data/varname/varsave_lr.csv')
VarSave1 = list(VarSave1.ix[:,0])

In [52]:
features1_save = features1[['uid']+VarSave1].drop_duplicates(['uid'])
TrainSet = pd.merge(usertarget,features1_save,how='left',on='uid')

In [231]:
ConVarSave=['借款状态_2','借款状态_3','借款状态_3比例','借款状态_1比例','批贷期数_均值','还款状态次数_1','还款状态次数_9',\
            '出现最多还款状态_比例','age','逾期特征_条数','欠款特征_欠款总额','芝麻F2_total','zmxyScore']

In [296]:
VarSave = CatVarSave + ConVarSave
TrainSet = features[['uid','target']+VarSave]

In [297]:
len(TrainSet),len(TrainSet.ix[0,:]),list(TrainSet.columns)[0:3]

(79989, 39, ['uid', 'target', '批贷期数_均值'])

In [54]:
start = time.clock()
var_name = list(TrainSet.columns)
var_name = list(set(var_name)^set(['uid','target']))
target = TrainSet['target']
users = TrainSet['uid']
X_Train,X_Test,y_train,y_test = cross_validation.train_test_split(TrainSet,target,test_size=0.2,random_state=27, \
                                                                  stratify=target)
X_train = X_Train[var_name]
X_test = X_Test[var_name]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.03 s


In [55]:
#xgboost
def modelfit(alg,trainset,train_target,testset,test_target,users,useTrainCV=True,cv_folds=5,early_stopping_rounds=50):
    if useTrainCV:
        xgb_param = alg.get_xgb_params()
        xgtrain = xgb.DMatrix(trainset.values, label=train_target.values)
        cvresult = xgb.cv(xgb_param, xgtrain, num_boost_round=alg.get_params()['n_estimators'], nfold=cv_folds,
            metrics='auc', early_stopping_rounds=early_stopping_rounds,)
        alg.set_params(n_estimators=cvresult.shape[0])

    #Fit the algorithm on the data
    alg.fit(trainset,train_target,eval_metric='auc')
    #feature_importance = sorted(alg.feature_importances_,reverse=True)
    
#     var_name = list(trainset.columns)
#     top10 = feature_importance[0:10]
#     top10_var = [var_name[feature_importance.index(impor)] for impor in top10]
#     print("\n".join(top10_var))
#     print(top10)
    
    #Predict training set:
    dtrain_predictions = alg.predict(trainset)
    dtrain_predprob = alg.predict_proba(trainset)[:,1]
    
    #Predict testing set:
    dtest_predictions = alg.predict(testset)
    dtest_predprob = alg.predict_proba(testset)[:,1]
    pre = pd.DataFrame([users,list(dtest_predictions),list(dtest_predprob)]).T
    pre.columns = ['userId','dtest_predictions','dtest_predprob']
    
    
    #Print model report:
    print ("Model Report")
    print ("Accuracy : %.4g" % metrics.accuracy_score(train_target.values, dtrain_predictions))
    print("precision (Train): %.4g" % metrics.precision_score(train_target.values, dtrain_predictions))
    print("recall (Train): %.4g" % metrics.recall_score(train_target.values, dtrain_predictions))
    print("F1_score (Train): %.4g" % metrics.f1_score(train_target.values, dtrain_predictions))
    print("AUC Score (Train): %f" % metrics.roc_auc_score(train_target.values, dtrain_predprob))
    print("confusion_matrix (Train):")
    print(metrics.confusion_matrix(train_target.values, dtrain_predictions))
    
    print ("Accuracy : %.4g" % metrics.accuracy_score(test_target.values, dtest_predictions))
    print("precision (Test): %.4g" % metrics.precision_score(test_target.values, dtest_predictions))
    print("recall (Test): %.4g" % metrics.recall_score(test_target.values, dtest_predictions))
    print("F1_score (Test): %.4g" % metrics.f1_score(test_target.values, dtest_predictions))
    print("AUC Score (Test): %f" % metrics.roc_auc_score(test_target.values, dtest_predprob))
    print("confusion_matrix (Test):")
    print(metrics.confusion_matrix(test_target.values, dtest_predictions))
    
    
    feature_importances_df=pd.DataFrame({'features':trainset.columns,'score':alg.feature_importances_})
    feature_importances_df.sort_values('score', ascending = False).head(10)
    return(feature_importances_df,pre)

In [56]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance,pre_result = modelfit(xgb1,X_train,y_train,X_test,y_test,list(X_Test.uid))
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.5823
precision (Train): 0.5782
recall (Train): 0.7107
F1_score (Train): 0.6376
AUC Score (Train): 0.614558
confusion_matrix (Train):
[[ 7550  9427]
 [ 5259 12920]]
Accuracy : 0.5598
precision (Test): 0.5603
recall (Test): 0.6909
F1_score (Test): 0.6188
AUC Score (Test): 0.579774
confusion_matrix (Test):
[[1780 2464]
 [1405 3140]]
run time: 2.00 min 40.09 s


In [60]:
User = tuple(list(pre_result.userId))

In [59]:
sql = """select uid,overduedays,case when overduedays = 0 then 0 else 1 end as label,loan_time
        from ydata where startDate > '2017-10-14' and endDate < '2017-12-5' and uid in {uid}""".format(uid=User)


8789

In [316]:
#所有筛选后的变量
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance = modelfit(xgb1,X_train,y_train,X_test,y_test)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.717
precision (Train): 0.6707
recall (Train): 0.2807
F1_score (Train): 0.3957
AUC Score (Train): 0.706949
confusion_matrix (Train):
[[39952  2912]
 [15197  5930]]
Accuracy : 0.7129
precision (Test): 0.6513
recall (Test): 0.2808
F1_score (Test): 0.3924
AUC Score (Test): 0.688683
confusion_matrix (Test):
[[9922  794]
 [3799 1483]]
run time: 24.00 min 6.50 s


In [317]:
features_importance

features     score
0                         批贷期数_均值  0.081655
1    one_hot_V3_V_BC_CN_MA_UL180D  0.020142
2                        借款状态_3比例  0.047360
3                         SMS_已逾期  0.094720
4            one_hot_F1_not_match  0.011432
5                       zmxyScore  0.131737
6                        借款状态_1比例  0.039739
7    one_hot_V3_V_BC_CN_MA_UM360D  0.011432
8      one_hot_relatStatus_single  0.011432
9                  one_hot_female  0.016331
10                         借款状态_3  0.028851
11    one_hot_relatStatus_married  0.007621
12  one_hot_final_decision_Reject  0.015787
13                         借款状态_2  0.041372
14                       还款状态次数_4  0.002722
15             one_hot_F1_have_F1  0.005988
16                       还款状态次数_9  0.043549
17                one_hot_rOs_iOS  0.008165
18                            age  0.078389
19                      欠款特征_欠款总额  0.033751
20                   逾期特征_一天最大逾期数  0.016875
21  one_hot_final_decision_Review  0.005988
22                     芝麻F2_total  0.015787
23                    借款状态_众数_2.0  0.002177
24                        逾期特征_条数  0.053348
25                    借款状态_众数_1.0  0.000544
26                       还款状态次数_1  0.037017
27                           有过欠款  0.017964
28                   one_hot_male  0.003266
29            one_hot_rOs_Android  0.014154
30            one_hot_ANDROID_APP  0.014698
31                    批贷期数_众数_0.0  0.001633
32                    批贷期数_众数_1.0  0.003811
33                one_hot_F1_fail  0.007077
34                    出现最多还款状态_比例  0.059336
35                one_hot_DEFAULT  0.010343
36                       还款状态次数_3  0.003811

In [318]:
VarAfterModel = []
for i in range(len(features_importance)):
    if features_importance.ix[i,1] > 0.01:
        VarAfterModel.append(features_importance.ix[i,0])

In [320]:
TrainSet = features[['uid','target']+VarAfterModel]

In [322]:
start = time.clock()
var_name = list(TrainSet.columns)
var_name = list(set(var_name)^set(['uid','target']))
target = TrainSet['target']
users = TrainSet['uid']
X_Train,X_Test,y_train,y_test = cross_validation.train_test_split(TrainSet,target,test_size=0.2,random_state=27, \
                                                                  stratify=target)
X_train = X_Train[var_name]
X_test = X_Test[var_name]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.06 s


In [323]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance = modelfit(xgb1,X_train,y_train,X_test,y_test)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.7165
precision (Train): 0.6694
recall (Train): 0.2794
F1_score (Train): 0.3942
AUC Score (Train): 0.704719
confusion_matrix (Train):
[[39949  2915]
 [15225  5902]]
Accuracy : 0.7122
precision (Test): 0.6492
recall (Test): 0.2793
F1_score (Test): 0.3905
AUC Score (Test): 0.687294
confusion_matrix (Test):
[[9919  797]
 [3807 1475]]
run time: 22.00 min 34.63 s


In [324]:
features_importance

features     score
0                         批贷期数_均值  0.091135
1    one_hot_V3_V_BC_CN_MA_UL180D  0.022939
2                         SMS_已逾期  0.094234
3                        借款状态_3比例  0.037198
4            one_hot_F1_not_match  0.019219
5                       zmxyScore  0.139492
6                        借款状态_1比例  0.034718
7    one_hot_V3_V_BC_CN_MA_UM360D  0.011779
8      one_hot_relatStatus_single  0.010539
9                  one_hot_female  0.022939
10                         借款状态_3  0.029758
11  one_hot_final_decision_Reject  0.030378
12                         借款状态_2  0.032238
13                       还款状态次数_9  0.054557
14                            age  0.082455
15                      欠款特征_欠款总额  0.032858
16                   逾期特征_一天最大逾期数  0.014879
17                     芝麻F2_total  0.019219
18                        逾期特征_条数  0.060136
19                       还款状态次数_1  0.034718
20                           有过欠款  0.023559
21            one_hot_rOs_Android  0.027278
22            one_hot_ANDROID_APP  0.014879
23                    出现最多还款状态_比例  0.050217
24                one_hot_DEFAULT  0.008679

In [312]:
#2017-10-15号之后的
start = time.clock()
var_name1 = list(TrainSet1.columns)
var_name1 = list(set(var_name1)^set(['uid','target']))
target1 = TrainSet1['target']
users1 = TrainSet1['uid']
X_Train1,X_Test1,y_train1,y_test1 = cross_validation.train_test_split(TrainSet1,target1,test_size=0.2,random_state=27, \
                                                                  stratify=target1)
X_train1 = X_Train1[var_name1]
X_test1 = X_Test1[var_name1]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.03 s


In [314]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance = modelfit(xgb1,X_train1,y_train1,X_test1,y_test1)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.5994
precision (Train): 0.5991
recall (Train): 0.7903
F1_score (Train): 0.6815
AUC Score (Train): 0.635988
confusion_matrix (Train):
[[ 6434 10806]
 [ 4285 16147]]
Accuracy : 0.5809
precision (Test): 0.5859
recall (Test): 0.7755
F1_score (Test): 0.6675
AUC Score (Test): 0.605750
confusion_matrix (Test):
[[1510 2800]
 [1147 3961]]
run time: 8.00 min 11.91 s


In [335]:
features_importance

features     score
0                         批贷期数_均值  0.091135
1    one_hot_V3_V_BC_CN_MA_UL180D  0.022939
2                         SMS_已逾期  0.094234
3                        借款状态_3比例  0.037198
4            one_hot_F1_not_match  0.019219
5                       zmxyScore  0.139492
6                        借款状态_1比例  0.034718
7    one_hot_V3_V_BC_CN_MA_UM360D  0.011779
8      one_hot_relatStatus_single  0.010539
9                  one_hot_female  0.022939
10                         借款状态_3  0.029758
11  one_hot_final_decision_Reject  0.030378
12                         借款状态_2  0.032238
13                       还款状态次数_9  0.054557
14                            age  0.082455
15                      欠款特征_欠款总额  0.032858
16                   逾期特征_一天最大逾期数  0.014879
17                     芝麻F2_total  0.019219
18                        逾期特征_条数  0.060136
19                       还款状态次数_1  0.034718
20                           有过欠款  0.023559
21            one_hot_rOs_Android  0.027278
22            one_hot_ANDROID_APP  0.014879
23                    出现最多还款状态_比例  0.050217
24                one_hot_DEFAULT  0.008679

In [336]:
VarSave

['有过欠款',
 '还款状态次数_3',
 '还款状态次数_4',
 '借款状态_众数_1.0',
 '借款状态_众数_2.0',
 '批贷期数_众数_0.0',
 '批贷期数_众数_1.0',
 'one_hot_female',
 'one_hot_male',
 'one_hot_ANDROID_APP',
 'one_hot_DEFAULT',
 'one_hot_rOs_Android',
 'one_hot_rOs_iOS',
 'one_hot_relatStatus_married',
 'one_hot_relatStatus_single',
 '逾期特征_一天最大逾期数',
 'one_hot_V3_V_BC_CN_MA_UL180D',
 'one_hot_V3_V_BC_CN_MA_UM360D',
 'one_hot_F1_fail',
 'one_hot_F1_have_F1',
 'one_hot_F1_not_match',
 '借款状态_2',
 '借款状态_3',
 '借款状态_3比例',
 '借款状态_1比例',
 '批贷期数_均值',
 '还款状态次数_1',
 '还款状态次数_9',
 '出现最多还款状态_比例',
 'age',
 '逾期特征_条数',
 '欠款特征_欠款总额',
 '芝麻F2_total',
 'zmxyScore']

In [333]:
pd.DataFrame(VarSave).to_csv(r'/home/heyang/data/varname/varsave_lr.csv',index=False)

In [337]:
#用所有的数据做训练集，测试集只用10-15号之后的

In [339]:
len(features),len(features.ix[0,:]),len(VarSave)

(79989, 805, 34)

In [ ]:
#10-15号之后首借逾期的uid


(63991, 15998)

In [61]:
# 通过逐步回归筛选变量，然后通过筛选后的变量用逻辑回归

In [ ]:
def stageWise(xArr,yArr,step=0.01,numIt=100):  
    xMat = mat(xArr)
    xMat = regularize(xMat)
    yMat = mat(yArr).T
    yMean = mean(yMat)
    yMat = yMat - yMean
    N, n = shape(xMat)  
    returnMat = zeros((numIt, n))
    ws = zeros((n,1))  
    wsTest = ws.copy()  
    weMax = ws.copy()  
    for ii in range(numIt):  
        print ws.T
        lowestErr = inf  
        for jj in range(n) :  
            for sign in [-1,1] :  
                wsTest = ws.copy()  
                wsTest[jj] += step*sign  
                yTest = xMat*wsTest  
                rssE = rssError(yMat.A, yTest.A)  
                if rssE < lowestErr :  
                    lowestErr = rssE  
                    wsMax = wsTest  
        ws = wsMax.copy()  
        returnMat[ii,:] = ws.T  
    return returnMat

In [ ]:
start = time.clock()
sql = 'select * from lr_91;'
features_td = pd.read_sql(sql,engine_2)
features_td = pd.merge(userTarget,features_td,how='left',on='uid')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))