In [1]:
from scipy import stats
from sklearn import datasets,linear_model,discriminant_analysis,cross_validation
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import time
import gc
import json
import scipy.stats as ss
from scipy.stats import chi2_contingency
from scipy.stats import mode
from Library import get_sample
from Library import optimal_binning
from sklearn import cross_validation,metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn import linear_model
from sklearn import ensemble
from sklearn.ensemble import GradientBoostingClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.grid_search import GridSearchCV
import xgboost as xgb
from sqlalchemy.engine import create_engine
engine_1 = create_engine(
        'mysql+pymysql://ro:cKqj4E3$K7GGeqs@nshd-slave-bi.mysql.rds.aliyuncs.com/paydayloan?charset=utf8',
        echo=False,pool_size=20, max_overflow=0)
engine_2 = create_engine(
    'mysql+pymysql://riskcontrol:tuLwJ3G6FLwR6t4A@nshd-risk.mysql.rds.aliyuncs.com/riskcontrol?charset=utf8',
    echo=False)

/usr/local/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py:1078: UserWarning: Illegal line #210
	"			 Verdana, Geneva, Lucid, Arial, Helvetica, Avant Garde, 
"
	in file "/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc"
  warnings.warn('Illegal %s' % error_details)
/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py:1078: UserWarning: Illegal line #211
	"			sans-serif
"
	in file "/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc"
  warnings.warn('Illegal %s' % error_details)


In [2]:
sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata \
            where startDate >= '2017-10-15')a \
        where overduedays is not null and uid >= 100;"
users = pd.read_sql(sql,engine_2)

sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata \
            where startDate >= '2017-10-15')a \
        where overduedays is not null and overduedays > 0 and uid >= 100;"
users1 = pd.read_sql(sql,engine_2)

sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata)a \
        where overduedays is not null and uid >= 100;"
Users = pd.read_sql(sql,engine_2)

sql = "select distinct uid from \
        ( \
            select uid,startDate,endDate,loan_time,case when overduedays is null and endDate < curdate() then curdate()-endDate else overduedays end as overduedays,repayAt \
            from ydata)a \
        where overduedays is not null and overduedays > 0 and loan_time = 1 and uid >= 100;"
Users1 = pd.read_sql(sql,engine_2)

In [3]:
#总的数据
#user对应的label
start = time.clock()
Users = list(Users.uid)
Users1 = list(Users1.uid)
Label = [1 if Users[i] in Users1 else 0 for i in range(len(Users))]
userTarget = pd.DataFrame([Users,Label]).T
userTarget.columns = ['userId','target']
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

KeyboardInterrupt: 

In [32]:
#2017-10-15号之后的数据
#user对应的label
start = time.clock()
users = list(users.uid)
users1 = list(users1.uid)
label = [1 if users[i] in users1 else 0 for i in range(len(users))]
usertarget = pd.DataFrame([users,label]).T
usertarget.columns = ['userId','target']
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 21.25 s


In [15]:
def DividConCat(features_df):
    start = time.clock()
    #将变量分为离散变量和连续变量
    var_name = list(features_df.columns)
    try:
        var_name.remove('userId')
        var_name.remove('target')
    except:
        0
    data = features_df.fillna(-1)
    target = list(features_df['target'])
    ConVar = []
    CatVar = []
    for var in var_name:
        values = list(data[var])
    #     values_1 = [values[i] for i in range(len(values)) if target[i] == 1]
        if len(list(set(values))) < 6:
            CatVar.append(var)
    #         thread = 0
    #         for val in values:
    #             if values.count(val)/len(values) > 0.9 and values_1.count(val)/len(values_1) > 0.9:
    #                 thread = 1
    #                 break
    #         if thread == 0:
    #             CatVar.append(var)
    #     else:
        else:
            ConVar.append(var)
    features_df_con = features_df[['userId','target']+ConVar]
    features_df_cat = features_df[['userId','target']+CatVar]
    end = time.clock()
    print("run time: %.2f min %.2f s" % divmod((end - start), 60))
    return(ConVar,CatVar,features_df_con,features_df_cat)

In [16]:
# 两个分类变量的相关性检验(转化为独立性检验)
# 以及关联系数(Phi coefficient,又称作 Cramer's statistic)
def CatVarCorrP(features_df,CatVar):
    """ calculate Cramers V statistic for categorial-categorial association.
        uses correction from Bergsma and Wicher, 
        Journal of the Korean Statistical Society 42 (2013): 323-328
    """
    #离散变量的筛选
    start = time.clock()
    target = features_df.target
    dic_var_corrp = {}
    for var in CatVar:
        values = features_df[var]
        confusion_matrix = pd.crosstab(target,values)
        chi2,p,dof,expected = ss.chi2_contingency(confusion_matrix)
        n = confusion_matrix.sum().sum()
        phi2 = chi2/n
        r,k = confusion_matrix.shape
        phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))    
        rcorr = r - ((r-1)**2)/(n-1)
        kcorr = k - ((k-1)**2)/(n-1)
        corr = np.sqrt(phi2corr / min((kcorr-1), (rcorr-1)))
        dic_var_corrp[var] = [corr,p]
    end = time.clock()
    print("run time: %.2f min %.2f s" % divmod((end - start), 60))
    return(dic_var_corrp)

In [17]:
#卡方检验
def CatVarChi(features_df,CatVar):
    start = time.clock()
    dic_var_pval = {}
    data = features_df.fillna(-1)
    target = list(features_df['target'])
    for var in CatVar:
        values = list(data[var])
        values_0 = [values[i] for i in range(len(values)) if target[i]==0]
        values_1 = [values[i] for i in range(len(values)) if target[i]==1]
        stand = list(set(values))
        chi_0 = []
        chi_1 = []
        for val in stand:
            if val != -1:
                chi_0.append(values_0.count(val))
                chi_1.append(values_1.count(val))
        chi = np.array([chi_0,chi_1])
        chi_result = chi2_contingency(chi)
        dic_var_pval[var] = chi_result[1]
    end = time.clock()
    print("run time: %.2f min %.2f s" % divmod((end - start), 60))
    return(dic_var_pval)

In [13]:
start = time.clock()
sql = 'select * from feature_llw;'
features_llw = pd.read_sql(sql,engine_2)
features_llw = pd.merge(userTarget,features_llw,how='left',on='userId')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 1.00 min 1.24 s


In [20]:
ConVar,CatVar,features_llw_con,features_llw_cat = DividConCat(features_llw)
features_llw_con.to_csv(r'/home/heyang/data/features_llw/features_llw.csv',index=False)
dic_llwvar_corrp = CatVarCorrP(features_llw,CatVar)
dic_llwvar_chipval = CatVarChi(features_llw,CatVar)

run time: 0.00 min 2.53 s
run time: 0.00 min 1.12 s
run time: 0.00 min 3.79 s


In [26]:
varvalues = []
for var in dic_llwvar_corrp.keys():
    varval = [var]
    varval = varval + dic_llwvar_corrp[var]
    varval.append(dic_llwvar_chipval[var])
    varvalues.append(varval)
varvalues = pd.DataFrame(varvalues,columns=['varname','corr','p','chip'])

In [30]:
varvalues.to_csv(r'/home/heyang/data/features_llw/catvarindex.csv',index=False)

In [28]:
CatVarSave = []
varvalues_fill = varvalues.fillna(0)
for i in range(len(varvalues_fill)):
    if varvalues_fill.ix[i,1] > 0.05 and varvalues_fill.ix[i,2] < 0.01 and varvalues_fill.ix[i,3] < 0.01:
        CatVarSave.append(varvalues_fill.ix[i,0])

In [29]:
CatVarSave

['7天内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '欺诈fail_芝麻',
 '7天内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 'query_result_芝麻',
 '欺诈not_match_芝麻',
 '1个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '7天内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '18个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '近60个月以上申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '6个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '12个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '24个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '7天内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾']

In [67]:
ConVarSave = ['zmxy_fraud_fetch_biz_code_AA_芝麻','zmxy_fraud_fetch_type_AA001_芝麻','zmxy_fraud_fetch命中项数_芝麻',\
              '6个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',\
              '6个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',\
              '18个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',\
              '近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
              '12个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',\
              '24个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',\
              '18个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',\
              '近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',\
              '12个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',\
              '24个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',\
              '通过贷款总额度_91','贷款总期数_91','通过贷款额度最大值_91','通过贷款均值_91','zmxyScore_芝麻',\
              '12个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',\
              '18个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',\
              '24个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',\
              '近60个月以上申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',\
              '6个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',\
              '1个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',\
              '3个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾']

In [ ]:
#2017-10-15号之后的数据

In [34]:
start = time.clock()
sql = 'select * from feature_llw;'
features1_llw = pd.read_sql(sql,engine_2)
features1_llw = pd.merge(usertarget,features1_llw,how='left',on='userId')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 1.00 min 0.65 s


In [35]:
ConVar,CatVar,features1_llw_con,features1_llw_cat = DividConCat(features1_llw)
features1_llw_con.to_csv(r'/home/heyang/data/features_llw/features1_llw.csv',index=False)
dic_llwvar_corrp1 = CatVarCorrP(features1_llw,CatVar)
dic_llwvar_chipval1 = CatVarChi(features1_llw,CatVar)

run time: 0.00 min 1.56 s
run time: 0.00 min 1.07 s
run time: 0.00 min 2.58 s


In [36]:
varvalues1 = []
for var in dic_llwvar_corrp1.keys():
    varval = [var]
    varval = varval + dic_llwvar_corrp1[var]
    varval.append(dic_llwvar_chipval1[var])
    varvalues1.append(varval)
varvalues1 = pd.DataFrame(varvalues1,columns=['varname','corr','p','chip'])

In [40]:
varvalues1.to_csv(r'/home/heyang/data/features_llw/catvarindex1.csv',index=False)

In [96]:
CatVarSave1 = []
varvalues1_fill = varvalues1.fillna(0)
for i in range(len(varvalues1_fill)):
    if varvalues1_fill.ix[i,1] > 0.02 and varvalues1_fill.ix[i,2] < 0.01 and varvalues1_fill.ix[i,3] < 0.01:
        CatVarSave1.append(varvalues1_fill.ix[i,0])

In [97]:
CatVarSave1

['逾期贷款总数_91',
 'query_result_芝麻',
 '欺诈not_match_芝麻',
 '3个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '6个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '6个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '18个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '12个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '24个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '18个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '12个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '24个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人身份证详情互联网金融门户_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人手机详情互联网金融门户_同盾']

In [98]:
ConVarSave1 = ['key_7_短信','1个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾',\
               '1个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',\
               '24个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',\
               '24个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',\
               '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾',\
               '18个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',\
               '18个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',\
               '近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',\
               '近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',\
               '12个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',\
               '12个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',\
               '3个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾',\
               '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情小额贷款公司_同盾',\
               '1个月内申请人在多个平台申请借款platform_detail借款人手机详情P2P网贷_同盾',\
               '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',\
               '3个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾',\
               '6个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾']

In [48]:
#model

In [50]:
start = time.clock()
sql = 'select * from feature_llw;'
features_llw = pd.read_sql(sql,engine_2)
features_llw = pd.merge(userTarget,features_llw,how='left',on='userId')
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 59.32 s


In [76]:
VarSave = CatVarSave + ConVarSave
TrainSet = features_llw[['userId','target']+VarSave]

In [77]:
start = time.clock()
var_name = list(TrainSet.columns)
var_name = list(set(var_name)^set(['userId','target']))
target = TrainSet['target']
users = TrainSet['userId']
X_Train,X_Test,y_train,y_test = cross_validation.train_test_split(TrainSet,target,test_size=0.2,random_state=27, \
                                                                  stratify=target)
X_train = X_Train[var_name]
X_test = X_Test[var_name]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.08 s


In [78]:
#xgboost
def modelfit(alg,trainset,train_target,testset,test_target,useTrainCV=True,cv_folds=5,early_stopping_rounds=50):
    if useTrainCV:
        xgb_param = alg.get_xgb_params()
        xgtrain = xgb.DMatrix(trainset.values, label=train_target.values)
        cvresult = xgb.cv(xgb_param, xgtrain, num_boost_round=alg.get_params()['n_estimators'], nfold=cv_folds,
            metrics='auc', early_stopping_rounds=early_stopping_rounds,)
        alg.set_params(n_estimators=cvresult.shape[0])

    #Fit the algorithm on the data
    alg.fit(trainset,train_target,eval_metric='auc')
    #feature_importance = sorted(alg.feature_importances_,reverse=True)
    
#     var_name = list(trainset.columns)
#     top10 = feature_importance[0:10]
#     top10_var = [var_name[feature_importance.index(impor)] for impor in top10]
#     print("\n".join(top10_var))
#     print(top10)
    
    #Predict training set:
    dtrain_predictions = alg.predict(trainset)
    dtrain_predprob = alg.predict_proba(trainset)[:,1]
    
    #Predict testing set:
    dtest_predictions = alg.predict(testset)
    dtest_predprob = alg.predict_proba(testset)[:,1]

    #Print model report:
    print ("Model Report")
    print ("Accuracy : %.4g" % metrics.accuracy_score(train_target.values, dtrain_predictions))
    print("precision (Train): %.4g" % metrics.precision_score(train_target.values, dtrain_predictions))
    print("recall (Train): %.4g" % metrics.recall_score(train_target.values, dtrain_predictions))
    print("F1_score (Train): %.4g" % metrics.f1_score(train_target.values, dtrain_predictions))
    print("AUC Score (Train): %f" % metrics.roc_auc_score(train_target.values, dtrain_predprob))
    print("confusion_matrix (Train):")
    print(metrics.confusion_matrix(train_target.values, dtrain_predictions))
    
    print ("Accuracy : %.4g" % metrics.accuracy_score(test_target.values, dtest_predictions))
    print("precision (Test): %.4g" % metrics.precision_score(test_target.values, dtest_predictions))
    print("recall (Test): %.4g" % metrics.recall_score(test_target.values, dtest_predictions))
    print("F1_score (Test): %.4g" % metrics.f1_score(test_target.values, dtest_predictions))
    print("AUC Score (Test): %f" % metrics.roc_auc_score(test_target.values, dtest_predprob))
    print("confusion_matrix (Test):")
    print(metrics.confusion_matrix(test_target.values, dtest_predictions))
    
    
    feature_importances_df=pd.DataFrame({'features':trainset.columns,'score':alg.feature_importances_})
    feature_importances_df.sort_values('score', ascending = False).head(10)
    return(feature_importances_df)

In [79]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance = modelfit(xgb1,X_train,y_train,X_test,y_test)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.6877
precision (Train): 0.6156
recall (Train): 0.1441
F1_score (Train): 0.2335
AUC Score (Train): 0.637824
confusion_matrix (Train):
[[40963  1901]
 [18083  3044]]
Accuracy : 0.6887
precision (Test): 0.6185
recall (Test): 0.1492
F1_score (Test): 0.2404
AUC Score (Test): 0.624290
confusion_matrix (Test):
[[10230   486]
 [ 4494   788]]
run time: 16.00 min 27.56 s


In [80]:
features_importance

features     score
0     1个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.008264
1    24个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.001033
2    6个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.008264
3                                          通过贷款总额度_91  0.138430
4                                           欺诈fail_芝麻  0.013430
5                     zmxy_fraud_fetch_biz_code_AA_芝麻  0.032025
6                             zmxy_fraud_fetch命中项数_芝麻  0.023760
7     6个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.003099
8      7天内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.009298
9    18个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.013430
10  近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情第三方服务...  0.001033
11     7天内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.007231
12  12个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.004132
13   1个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.013430
14   12个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.000000
15    7天内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.003099
16      1个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.008264
17  24个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.002066
18                                       通过贷款额度最大值_91  0.071281
19   近60个月以上申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.009298
20    1个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.014463
21    3个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.022727
22     18个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.004132
23                                          通过贷款均值_91  0.155992
24                                       zmxyScore_芝麻  0.211777
25     24个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.001033
26   12个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.000000
27  近60个月以上申请人在多个平台申请借款platform_detail借款人座机详情第三方服务...  0.004132
28     12个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.000000
29   18个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.000000
30                                    query_result_芝麻  0.013430
31                                     欺诈not_match_芝麻  0.014463
32                                           贷款总期数_91  0.127066
33                     zmxy_fraud_fetch_type_AA001_芝麻  0.024793
34  18个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.001033
35      3个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.002066
36   24个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.000000
37   3个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.014463
38       7天内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.006198
39      6个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.000000
40    6个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.007231
41  近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情第三方服...  0.003099
42    3个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.001033

In [82]:
VarAfterModel = []
for i in range(len(features_importance)):
    if features_importance.ix[i,1] > 0.001:
        VarAfterModel.append(features_importance.ix[i,0])

In [84]:
TrainSet = features_llw[['userId','target']+VarAfterModel]

In [85]:
start = time.clock()
var_name = list(TrainSet.columns)
var_name = list(set(var_name)^set(['userId','target']))
target = TrainSet['target']
users = TrainSet['userId']
X_Train,X_Test,y_train,y_test = cross_validation.train_test_split(TrainSet,target,test_size=0.2,random_state=27, \
                                                                  stratify=target)
X_train = X_Train[var_name]
X_test = X_Test[var_name]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.05 s


In [86]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance = modelfit(xgb1,X_train,y_train,X_test,y_test)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.6875
precision (Train): 0.6175
recall (Train): 0.141
F1_score (Train): 0.2295
AUC Score (Train): 0.637539
confusion_matrix (Train):
[[41019  1845]
 [18149  2978]]
Accuracy : 0.6878
precision (Test): 0.6159
recall (Test): 0.1448
F1_score (Test): 0.2345
AUC Score (Test): 0.624149
confusion_matrix (Test):
[[10239   477]
 [ 4517   765]]
run time: 2.00 min 45.16 s


In [87]:
features_importance

features     score
0     1个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.002967
1    24个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.005935
2    6个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.009891
3                                          通过贷款总额度_91  0.148368
4                                           欺诈fail_芝麻  0.010880
5                     zmxy_fraud_fetch_biz_code_AA_芝麻  0.031652
6                             zmxy_fraud_fetch命中项数_芝麻  0.029674
7     6个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.004946
8      7天内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.010880
9    18个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.001978
10  近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情第三方服务...  0.003956
11     7天内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.003956
12  12个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.005935
13   1个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.017804
14    7天内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.003956
15      1个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.009891
16  24个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.000000
17                                       通过贷款额度最大值_91  0.063304
18   近60个月以上申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.014837
19    1个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.008902
20    3个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.018793
21     18个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.000989
22                                          通过贷款均值_91  0.166172
23                                       zmxyScore_芝麻  0.213650
24     24个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.000000
25  近60个月以上申请人在多个平台申请借款platform_detail借款人座机详情第三方服务...  0.000989
26                                    query_result_芝麻  0.014837
27                                     欺诈not_match_芝麻  0.016815
28                                           贷款总期数_91  0.124629
29                     zmxy_fraud_fetch_type_AA001_芝麻  0.020772
30  18个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.000000
31      3个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.000989
32   3个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.014837
33       7天内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾  0.008902
34    6个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.006924
35  近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情第三方服...  0.000000
36    3个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾  0.000989

In [106]:
VarSave1 = ConVarSave1 + CatVarSave1
TrainSet1 = features1_llw[['userId','target']+VarSave1]

In [107]:
start = time.clock()
var_name1 = list(TrainSet1.columns)
var_name1 = list(set(var_name1)^set(['userId','target']))
target1 = TrainSet1['target']
users1 = TrainSet1['userId']
X_Train1,X_Test1,y_train1,y_test1 = cross_validation.train_test_split(TrainSet1,target1,test_size=0.2,random_state=27, \
                                                                  stratify=target1)
X_train1 = X_Train1[var_name1]
X_test1 = X_Test1[var_name1]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.03 s


In [108]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance1 = modelfit(xgb1,X_train1,y_train1,X_test1,y_test1)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.5914
precision (Train): 0.5966
recall (Train): 0.7615
F1_score (Train): 0.669
AUC Score (Train): 0.629037
confusion_matrix (Train):
[[ 6720 10520]
 [ 4873 15559]]
Accuracy : 0.5654
precision (Test): 0.5788
recall (Test): 0.7296
F1_score (Test): 0.6455
AUC Score (Test): 0.585853
confusion_matrix (Test):
[[1598 2712]
 [1381 3727]]
run time: 2.00 min 3.66 s


In [109]:
features_importance1

features     score
0      1个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾  0.065089
1     1个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾  0.047337
2    6个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.021696
3     3个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾  0.099606
4     1个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾  0.056213
5   近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情第三方服务...  0.005917
6    18个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.004931
7   3个月内申请人在多个平台申请借款platform_detail借款人身份证详情互联网金融门户_同盾  0.005917
8   12个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.010848
9    12个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾  0.050296
10                                           key_7_短信  0.091716
11    24个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾  0.048323
12  24个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.001972
13    6个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾  0.056213
14    12个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾  0.054241
15    3个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.002959
16   12个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.001972
17   18个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾  0.040434
18    1个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾  0.027613
19   3个月内申请人在多个平台申请借款platform_detail借款人手机详情互联网金融门户_同盾  0.004931
20                                    query_result_芝麻  0.021696
21   24个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾  0.032544
22                                     欺诈not_match_芝麻  0.013807
23  18个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.000986
24    18个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾  0.021696
25   1个月内申请人在多个平台申请借款platform_detail借款人身份证详情小额贷款公司_同盾  0.028600
26   24个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.000000
27                                          逾期贷款总数_91  0.016765
28   3个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾  0.008876
29  近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情coun...  0.026627
30     1个月内申请人在多个平台申请借款platform_detail借款人手机详情P2P网贷_同盾  0.051282
31    6个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾  0.002959
32  近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情第三方服...  0.000000
33    3个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾  0.056213
34  近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情count_同盾  0.019724

In [113]:
TrainSet = features_llw[['userId','target']+VarSaveAll]
start = time.clock()
var_name = list(TrainSet.columns)
var_name = list(set(var_name)^set(['userId','target']))
target = TrainSet['target']
users = TrainSet['userId']
X_Train,X_Test,y_train,y_test = cross_validation.train_test_split(TrainSet,target,test_size=0.2,random_state=27, \
                                                                  stratify=target)
X_train = X_Train[var_name]
X_test = X_Test[var_name]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.10 s


79989

In [111]:
VarSaveAll = list(set(VarSave + VarSave1))

In [115]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance = modelfit(xgb1,X_train,y_train,X_test,y_test)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.711
precision (Train): 0.6823
recall (Train): 0.233
F1_score (Train): 0.3474
AUC Score (Train): 0.697981
confusion_matrix (Train):
[[40572  2292]
 [16204  4923]]
Accuracy : 0.7012
precision (Test): 0.6394
recall (Test): 0.2175
F1_score (Test): 0.3246
AUC Score (Test): 0.664760
confusion_matrix (Test):
[[10068   648]
 [ 4133  1149]]
run time: 7.00 min 44.04 s


In [116]:
VarAfterModel = []
for i in range(len(features_importance)):
    if features_importance.ix[i,1] > 0.001:
        VarAfterModel.append(features_importance.ix[i,0])

In [117]:
TrainSet = features_llw[['userId','target']+VarAfterModel]

In [119]:
start = time.clock()
var_name = list(TrainSet.columns)
var_name = list(set(var_name)^set(['userId','target']))
target = TrainSet['target']
users = TrainSet['userId']
X_Train,X_Test,y_train,y_test = cross_validation.train_test_split(TrainSet,target,test_size=0.2,random_state=27, \
                                                                  stratify=target)
X_train = X_Train[var_name]
X_test = X_Test[var_name]
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

run time: 0.00 min 0.07 s


In [120]:
start = time.clock()
xgb1 = XGBClassifier(learning_rate =0.1,n_estimators=500,max_depth=4,min_child_weight=1,gamma=0,subsample=0.8,
                     colsample_bytree=0.8,objective= 'binary:logistic',nthread=-1,scale_pos_weight=1,seed=27)
features_importance = modelfit(xgb1,X_train,y_train,X_test,y_test)
end = time.clock()
print("run time: %.2f min %.2f s" % divmod((end - start), 60))

Model Report
Accuracy : 0.7103
precision (Train): 0.6855
recall (Train): 0.2265
F1_score (Train): 0.3405
AUC Score (Train): 0.689062
confusion_matrix (Train):
[[40669  2195]
 [16342  4785]]
Accuracy : 0.7027
precision (Test): 0.6501
recall (Test): 0.2156
F1_score (Test): 0.3239
AUC Score (Test): 0.664858
confusion_matrix (Test):
[[10103   613]
 [ 4143  1139]]
run time: 5.00 min 44.84 s


In [122]:
pd.DataFrame(VarAfterModel).to_csv(r'/home/heyang/data/varname/varsave_llw.csv',index=False,encoding='utf-8')

In [123]:
VarAfterModel

['1个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾',
 '24个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '6个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '通过贷款总额度_91',
 '3个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾',
 '欺诈fail_芝麻',
 'zmxy_fraud_fetch_biz_code_AA_芝麻',
 'zmxy_fraud_fetch命中项数_芝麻',
 '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',
 '6个月内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '7天内申请人在多个平台申请借款platform_detail借款人座机详情第三方服务商_同盾',
 '18个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人身份证详情互联网金融门户_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '12个月内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 '7天内申请人在多个平台申请借款platform_detail借款人手机详情第三方服务商_同盾',
 '12个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',
 '7天内申请人在多个平台申请借款platform_detail借款人身份证详情第三方服务商_同盾',
 'key_7_短信',
 '24个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',
 '1个月内申请人在多个平台申请借款platform_detail设备ID详情P2P网贷_同盾',
 '6个月内

In [124]:
VarSave1

['key_7_短信',
 '1个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',
 '24个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',
 '24个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾',
 '18个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',
 '18个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',
 '近60个月以上申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',
 '近60个月以上申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',
 '12个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',
 '12个月内申请人在多个平台申请借款platform_detail借款人手机详情count_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人身份证详情P2P网贷_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情小额贷款公司_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人手机详情P2P网贷_同盾',
 '1个月内申请人在多个平台申请借款platform_detail借款人身份证详情count_同盾',
 '3个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾',
 '6个月内申请人在多个平台申请借款platform_detail借款人手机详情小额贷款公司_同盾',
 '逾期贷款总数_91',
 'query_result_芝麻',
 '欺诈not_match_芝麻',
 '3个月内申请人在多个平台申请借款platform_detail借款人手机详情第三方